--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaDevGuy/CoinFlip
build-by-default: true
branches:
- master
projects:
  CoinFlip:
    path: ""
    icon: "assets/images/coin.png"
...
