name: BetterCoinFlip
main: DaDevGuy\BetterCoinFlip\Main
version: 1.0.0
api: 5.3.0
author: DaDevGuy
description: "A PocketMine-MP CoinFlip plugin made for 5.0 servers"

commands:
  flip:
    description: "Flip a Coin"
    usage: "/coinflip"
    permission: flip.coin

permissions:
  flip.coin:
    default: true